### ISSUE TITLE
Blank screen when sharing

### ISSUE THREAD

**Issue by JTravis76** [mikenunan/TransparentWindowWpf#1]
Hello, I thought I would check to see if anyone else attempted this and I found this project. Just curious, did this work for you when sharing a frame via MS Teams? All I get a blank / black screen. The application does work as expected. Able to see other windows behind the transparent frame, but when I select it to share during a Teams call. All I get is a blank screen.

Thank much,

**Comment by mikenunan** [comment]
Hi Travis,

Very sorry I missed the notification on this question of yours - if this is still relevant and you haven't already found it, please try https://github.com/mikenunan/ScreenMirror which should avoid the blank screen problem with Teams, at the cost of a bit of update latency.

Best regards,

Mike
